server:
  port: 7070
spring:
  application:
    name: service-provider
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka,http://localhost:8762/eureka/
  #度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
